/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JinaReaderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKeyEnvVar: "JINA_API_KEY",
  requireApiKey: false,
  loadDotEnvFromVaultRoot: true,
  dotEnvFileName: ".env",
  readerBaseUrl: "https://r.jina.ai/",
  timeoutSeconds: 60,
  accept: "text/plain; charset=utf-8",
  defaultBehavior: "replace",
  searchBaseUrl: "https://s.jina.ai/",
  searchResultCount: 5,
  searchType: "web",
  searchProvider: "default"
};
var JinaReaderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("API Key Environment Variable").setDesc("The name of the environment variable or .env key that contains the Jina API key.").addText((text) => text.setPlaceholder("JINA_API_KEY").setValue(this.plugin.settings.apiKeyEnvVar).onChange(async (value) => {
      this.plugin.settings.apiKeyEnvVar = value || DEFAULT_SETTINGS.apiKeyEnvVar;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Require API Key").setDesc("If enabled, the plugin will fail with an error message if the API key cannot be found.").addToggle((toggle) => toggle.setValue(this.plugin.settings.requireApiKey).onChange(async (value) => {
      this.plugin.settings.requireApiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Load .env from Vault Root").setDesc("Attempt to load a .env file from the Obsidian vault root directory.").addToggle((toggle) => toggle.setValue(this.plugin.settings.loadDotEnvFromVaultRoot).onChange(async (value) => {
      this.plugin.settings.loadDotEnvFromVaultRoot = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(".env File Name").setDesc("The name of the dotenv file to load from the vault root.").addText((text) => text.setPlaceholder(".env").setValue(this.plugin.settings.dotEnvFileName).onChange(async (value) => {
      this.plugin.settings.dotEnvFileName = value || DEFAULT_SETTINGS.dotEnvFileName;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Reader Base URL").setDesc("The Jina Reader base URL.").addText((text) => text.setPlaceholder("https://r.jina.ai/").setValue(this.plugin.settings.readerBaseUrl).onChange(async (value) => {
      this.plugin.settings.readerBaseUrl = value || DEFAULT_SETTINGS.readerBaseUrl;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Timeout (Seconds)").setDesc("HTTP request timeout in seconds.").addText((text) => text.setPlaceholder("60").setValue(this.plugin.settings.timeoutSeconds.toString()).onChange(async (value) => {
      const parsed = parseInt(value, 10);
      if (!isNaN(parsed) && parsed > 0) {
        this.plugin.settings.timeoutSeconds = parsed;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Accept Header").setDesc("HTTP Accept header for the request.").addText((text) => text.setPlaceholder("text/plain; charset=utf-8").setValue(this.plugin.settings.accept).onChange(async (value) => {
      this.plugin.settings.accept = value || DEFAULT_SETTINGS.accept;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Behavior").setDesc("The default behavior when fetching Markdown content.").addDropdown((dropdown) => dropdown.addOption("replace", "Replace").addOption("insert_below", "Insert Below").setValue(this.plugin.settings.defaultBehavior).onChange(async (value) => {
      this.plugin.settings.defaultBehavior = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Jina Search" });
    new import_obsidian.Setting(containerEl).setName("Search Base URL").setDesc("The Jina Search endpoint.").addText((text) => text.setPlaceholder("https://s.jina.ai/").setValue(this.plugin.settings.searchBaseUrl).onChange(async (value) => {
      this.plugin.settings.searchBaseUrl = value || DEFAULT_SETTINGS.searchBaseUrl;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Search Result Count").setDesc("Number of results to request, from 1 to 20.").addText((text) => text.setPlaceholder("5").setValue(this.plugin.settings.searchResultCount.toString()).onChange(async (value) => {
      const parsed = parseInt(value, 10);
      if (!isNaN(parsed) && parsed >= 1 && parsed <= 20) {
        this.plugin.settings.searchResultCount = parsed;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Search Type").setDesc("Choose web, image, or news results.").addDropdown((dropdown) => dropdown.addOption("web", "Web").addOption("images", "Images").addOption("news", "News").setValue(this.plugin.settings.searchType).onChange(async (value) => {
      this.plugin.settings.searchType = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Search Provider").setDesc("Use the API default provider or select one explicitly.").addDropdown((dropdown) => dropdown.addOption("default", "Default").addOption("google", "Google").addOption("bing", "Bing").addOption("reader", "Reader").setValue(this.plugin.settings.searchProvider).onChange(async (value) => {
      this.plugin.settings.searchProvider = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/urlDetection.ts
var URL_REGEX = /https?:\/\/[^\s)\]>"]+/i;
function extractUrlFromText(text) {
  const match = text.match(URL_REGEX);
  return match ? match[0] : null;
}
function detectUrl(editor) {
  const selection = editor.getSelection();
  if (selection) {
    const url = extractUrlFromText(selection);
    if (url) {
      const cursor2 = editor.getCursor("from");
      return { url, lineIndex: cursor2.line };
    }
  }
  const cursor = editor.getCursor();
  const currentLine = editor.getLine(cursor.line);
  const urlFromLine = extractUrlFromText(currentLine);
  if (urlFromLine) {
    return { url: urlFromLine, lineIndex: cursor.line };
  }
  const lineCount = editor.lineCount();
  for (let i = 0; i < lineCount; i++) {
    const line = editor.getLine(i);
    const urlFromNote = extractUrlFromText(line);
    if (urlFromNote) {
      return { url: urlFromNote, lineIndex: i };
    }
  }
  return null;
}

// src/jinaReader.ts
var import_obsidian2 = require("obsidian");
async function fetchJinaReaderMarkdown(url, settings, apiKey) {
  let baseUrl = settings.readerBaseUrl;
  if (!baseUrl.endsWith("/")) {
    baseUrl += "/";
  }
  const targetUrl = baseUrl + encodeURIComponent(url);
  const headers = {
    "Accept": settings.accept
  };
  if (apiKey) {
    headers["Authorization"] = `Bearer ${apiKey}`;
  }
  const fetchPromise = (0, import_obsidian2.requestUrl)({
    url: targetUrl,
    method: "GET",
    headers,
    throw: false
  });
  const timeoutPromise = new Promise((_, reject) => {
    setTimeout(() => {
      reject(new Error("Request timed out"));
    }, settings.timeoutSeconds * 1e3);
  });
  try {
    const response = await Promise.race([fetchPromise, timeoutPromise]);
    if (response.status >= 400) {
      throw new Error(`HTTP Error ${response.status}: ${response.text}`);
    }
    return response.text;
  } catch (error) {
    throw error;
  }
}

// src/jinaSearch.ts
var import_obsidian3 = require("obsidian");
async function fetchJinaSearchMarkdown(query, settings, apiKey) {
  const normalizedQuery = query.trim();
  if (!normalizedQuery) {
    throw new Error("Search query cannot be empty");
  }
  if (!apiKey) {
    throw new Error("API key is required for Jina Search");
  }
  let baseUrl = settings.searchBaseUrl;
  if (!baseUrl.endsWith("/")) {
    baseUrl += "/";
  }
  const params = new URLSearchParams();
  params.set("type", settings.searchType);
  params.set("num", settings.searchResultCount.toString());
  if (settings.searchProvider !== "default") {
    params.set("provider", settings.searchProvider);
  }
  const targetUrl = `${baseUrl}${encodeURIComponent(normalizedQuery)}?${params.toString()}`;
  const headers = {
    "Accept": "text/plain",
    "Authorization": `Bearer ${apiKey}`
  };
  const searchPromise = (0, import_obsidian3.requestUrl)({
    url: targetUrl,
    method: "GET",
    headers,
    throw: false
  });
  const timeoutPromise = new Promise((_, reject) => {
    setTimeout(() => {
      reject(new Error("Search request timed out"));
    }, settings.timeoutSeconds * 1e3);
  });
  const response = await Promise.race([searchPromise, timeoutPromise]);
  if (response.status >= 400) {
    const details = response.text.trim().slice(0, 500);
    throw new Error(`Search HTTP ${response.status}${details ? `: ${details}` : ""}`);
  }
  const markdown = response.text.trim();
  if (!markdown) {
    throw new Error("Jina Search returned an empty response");
  }
  return markdown;
}

// src/dotenv.ts
function parseDotenv(content) {
  const result = {};
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const equalIndex = trimmed.indexOf("=");
    if (equalIndex === -1) {
      continue;
    }
    const key = trimmed.slice(0, equalIndex).trim();
    let value = trimmed.slice(equalIndex + 1).trim();
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    if (key) {
      result[key] = value;
    }
  }
  return result;
}

// src/main.ts
var ConfirmModal = class extends import_obsidian4.Modal {
  constructor(app, message, onConfirm, onCancel) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
    this.onCancel = onCancel;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    const buttonContainer = contentEl.createDiv({ attr: { style: "display: flex; gap: 10px; justify-content: flex-end; margin-top: 20px;" } });
    const confirmButton = buttonContainer.createEl("button", { text: "Yes, apply" });
    confirmButton.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
    const cancelButton = buttonContainer.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => {
      this.close();
      this.onCancel();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var SearchModal = class extends import_obsidian4.Modal {
  constructor(app, initialQuery, onSubmit) {
    super(app);
    this.initialQuery = initialQuery;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Search with Jina" });
    const input = contentEl.createEl("input", {
      attr: {
        type: "text",
        placeholder: "Enter a search query",
        "aria-label": "Jina Search query"
      }
    });
    input.value = this.initialQuery;
    input.style.width = "100%";
    const submit = () => {
      const query = input.value.trim();
      if (!query) {
        new import_obsidian4.Notice("Jina Search: Enter a search query.");
        return;
      }
      this.close();
      this.onSubmit(query);
    };
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        submit();
      }
    });
    const buttonContainer = contentEl.createDiv({
      attr: { style: "display: flex; justify-content: flex-end; margin-top: 16px;" }
    });
    const searchButton = buttonContainer.createEl("button", { text: "Search" });
    searchButton.addEventListener("click", submit);
    input.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var JinaReaderPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new JinaReaderSettingTab(this.app, this));
    this.addCommand({
      id: "jina-reader-fetch-default",
      name: "Fetch URL using Default Behavior",
      editorCallback: async (editor, view) => {
        await this.executeFetch(editor, view, "insert_below");
      }
    });
    this.addCommand({
      id: "jina-search-insert-results",
      name: "Search and insert results",
      editorCallback: (editor) => {
        const selectedQuery = editor.getSelection().trim();
        if (selectedQuery) {
          void this.executeSearch(editor, selectedQuery);
          return;
        }
        new SearchModal(this.app, "", (query) => {
          void this.executeSearch(editor, query);
        }).open();
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async resolveApiKey() {
    const keyName = this.settings.apiKeyEnvVar || "JINA_API_KEY";
    try {
      if (typeof process !== "undefined" && process.env && process.env[keyName]) {
        return process.env[keyName];
      }
    } catch (e) {
    }
    if (this.settings.loadDotEnvFromVaultRoot) {
      const dotEnvPath = this.settings.dotEnvFileName || ".env";
      const adapter = this.app.vault.adapter;
      if (await adapter.exists(dotEnvPath)) {
        try {
          const content = await adapter.read(dotEnvPath);
          const dotenvValues = parseDotenv(content);
          if (dotenvValues[keyName]) {
            return dotenvValues[keyName];
          }
        } catch (e) {
          new import_obsidian4.Notice(`Jina Reader: Error reading ${dotEnvPath} file.`);
        }
      } else if (this.settings.requireApiKey) {
        new import_obsidian4.Notice(`Jina Reader: ${dotEnvPath} file not found at vault root.`);
      }
    }
    return null;
  }
  async executeFetch(editor, view, behavior) {
    const urlMatch = detectUrl(editor);
    if (!urlMatch) {
      new import_obsidian4.Notice("Jina Reader: No URL found in the current selection, line, or note.");
      return;
    }
    const apiKey = await this.resolveApiKey();
    if (!apiKey && this.settings.requireApiKey) {
      new import_obsidian4.Notice(`Jina Reader: Missing API key. Expected in process.env or .env file as ${this.settings.apiKeyEnvVar}.`);
      return;
    }
    const initialContent = editor.getValue();
    new import_obsidian4.Notice("Jina Reader: fetching Markdown...");
    try {
      const markdown = await fetchJinaReaderMarkdown(urlMatch.url, this.settings, apiKey);
      const currentContent = editor.getValue();
      if (currentContent !== initialContent) {
        new ConfirmModal(this.app, "The note content changed while fetching. Do you still want to apply the fetched Markdown?", () => {
          this.applyMarkdown(editor, behavior, markdown, urlMatch);
        }, () => {
          new import_obsidian4.Notice("Jina Reader: Aborted applying Markdown.");
        }).open();
      } else {
        this.applyMarkdown(editor, behavior, markdown, urlMatch);
      }
    } catch (error) {
      console.error("Jina Reader Error:", error);
      new import_obsidian4.Notice(`Jina Reader Error: ${error.message}`);
    }
  }
  async executeSearch(editor, query) {
    const apiKey = await this.resolveApiKey();
    if (!apiKey) {
      new import_obsidian4.Notice(`Jina Search: API key is required. Please set ${this.settings.apiKeyEnvVar} in your .env file.`);
      return;
    }
    const initialContent = editor.getValue();
    const insertionPosition = editor.getCursor("to");
    new import_obsidian4.Notice("Jina Search: searching...");
    try {
      const results = await fetchJinaSearchMarkdown(query, this.settings, apiKey);
      const markdown = `## Jina Search: ${query.replace(/\s+/g, " ")}

${results}`;
      const insertResults = () => {
        const position = editor.getValue() === initialContent ? insertionPosition : editor.getCursor();
        editor.replaceRange(`

${markdown}`, position);
        new import_obsidian4.Notice("Jina Search: results inserted.");
      };
      if (editor.getValue() !== initialContent) {
        new ConfirmModal(
          this.app,
          "The note changed while searching. Insert the results at the current cursor?",
          insertResults,
          () => new import_obsidian4.Notice("Jina Search: Aborted inserting results.")
        ).open();
      } else {
        insertResults();
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error("Jina Search Error:", error);
      new import_obsidian4.Notice(`Jina Search Error: ${message}`);
    }
  }
  applyMarkdown(editor, behavior, markdown, urlMatch) {
    if (behavior === "replace") {
      editor.setValue(markdown);
      new import_obsidian4.Notice("Jina Reader: note replaced with Markdown.");
    } else if (behavior === "insert_below") {
      if (urlMatch.lineIndex !== null) {
        const lineContent = editor.getLine(urlMatch.lineIndex);
        editor.replaceRange(`

${markdown}`, { line: urlMatch.lineIndex, ch: lineContent.length });
      } else {
        const lastLine = editor.lineCount() - 1;
        const lastLineLength = editor.getLine(lastLine).length;
        editor.replaceRange(`

${markdown}`, { line: lastLine, ch: lastLineLength });
      }
      new import_obsidian4.Notice("Jina Reader: Markdown inserted.");
    } else {
      new import_obsidian4.Notice(`Jina Reader: Invalid behavior ${behavior}`);
    }
  }
};
